<a href="https://colab.research.google.com/github/AndresMontesDeOca/Analisis-de-Datos/blob/main/TP_Grupal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TP Grupal

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

pd.set_option('display.max_columns', None)

## Data Load

In [7]:
url = 'https://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2026-01-25/data/listings.csv.gz'
data = pd.read_csv(url)

print(data.info())
display(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27348 entries, 0 to 27347
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            27348 non-null  int64
 1   listing_url                                   27348 non-null  object
 2   scrape_id                                     27348 non-null  int64
 3   last_scraped                                  27348 non-null  object
 4   source                                        27348 non-null  object
 5   name                                          27348 non-null  object
 6   description                                   26752 non-null  object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   27347 non-null  object
 9   host_id                                       27348 non-null  int64
 10  host_url                                      27348 non-null  object
 11  host_profile_id                               27348 non-null  int64
 12  host_profile_url                              27348 non-null  object
 13  host_name                                     27348 non-null  object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      27348 non-null  int64
 16  hosts_time_as_user_months                     27348 non-null  int64
 17  hosts_time_as_host_years                      27348 non-null  int64
 18  hosts_time_as_host_months                     27348 non-null  int64
 19  host_location                                 21565 non-null  object
 20  host_about                                    15564 non-null  object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             27348 non-null  object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              27348 non-null  object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           27348 non-null  int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          27348 non-null  object
 32  host_identity_verified                        27348 non-null  object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        27348 non-null  object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      27348 non-null  float64
 37  longitude                                     27348 non-null  float64
 38  property_type                                 27348 non-null  object
 39  room_type                                     27348 non-null  object
 40  accommodates                                  27348 non-null  int64
 41  bathrooms                                     27340 non-null  float64
 42  bathrooms_text                                27337 non-null  object
 43  bedrooms                                      27288 non-null  float64
 44  beds                                          27340 non-null  float64
 45  amenities                                     27348 non-null  object
 46  price                                         0 non-null      float64
 47  minimum_nights                                27242 non-null  float64
 48  maximum_nights                                27242 non-null  float64
 49  minimum_minimum_nights                        27242 non-null  float64
 50  maximum_minimum_nights                        27242 non-null  float64
 51  minimum_maximum_nights                        27242 non-null  float64
 52  maximum_maximum_nights                        27242 non-null  float64
 53  minimum_nights_avg_ntm                        27348 non-null  float64
 54  maximum_nights_avg_ntm                        27348 non-null  float64
 55  calendar_updated                              0 non-null      float64
 56  has_availability                              27144 non-null  object
 57  availability_30                               27348 non-null  int64
 58  availability_60                               27348 non-null  int64
 59  availability_90                               27348 non-null  int64
 60  availability_365                              27348 non-null  int64
 61  calendar_last_scraped                         27348 non-null  object
 62  number_of_reviews                             27348 non-null  int64
 63  number_of_reviews_ltm                         27348 non-null  int64
 64  number_of_reviews_l30d                        27348 non-null  int64
 65  availability_eoy                              27348 non-null  int64
 66  number_of_reviews_ly                          27348 non-null  int64
 67  estimated_occupancy_l365d                     27348 non-null  int64
 68  estimated_revenue_l365d                       0 non-null      float64
 69  first_review                                  24045 non-null  object
 70  last_review                                   24045 non-null  object
 71  review_scores_rating                          24045 non-null  float64
 72  review_scores_accuracy                        24044 non-null  float64
 73  review_scores_cleanliness                     24045 non-null  float64
 74  review_scores_checkin                         24045 non-null  float64
 75  review_scores_communication                   24045 non-null  float64
 76  review_scores_location                        24045 non-null  float64
 77  review_scores_value                           24045 non-null  float64
 78  license                                       461 non-null    object
 79  instant_bookable                              0 non-null      float64
 80  calculated_host_listings_count                27348 non-null  int64
 81  calculated_host_listings_count_entire_homes   27348 non-null  int64
 82  calculated_host_listings_count_private_rooms  27348 non-null  int64
 83  calculated_host_listings_count_shared_rooms   27348 non-null  int64
 84  reviews_per_month                             24045 non-null  float64
dtypes: float64(36), int64(24), object(25)
memory usage: 17.7+ MB
None

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,42610838,https://www.airbnb.com/rooms/42610838,20260125052844,2026-01-25,city scrape,"Puerto Madero a 3 cuadras, centro, bello , tea...","Unbeatable location half a block away, 50 mete...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,224049389,https://www.airbnb.com/users/show/224049389,1469188629918707060,https://www.airbnb.com/users/profile/146918862...,Gabriela,NaN,7,2,5,11,NaN,NaN,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/ba7f6...,NaN,3,NaN,NaN,t,t,NaN,San Nicolas,NaN,-34.599976,-58.374195,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Kitchen"", ""Air conditioning"", ""Wifi"", ""TV""]",NaN,7.0,365.0,7.0,7.0,365.0,365.0,7.0,365.0,NaN,t,30,35,36,244,2026-01-25,0,0,0,220,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,0,0,NaN
1,1305876403852901802,https://www.airbnb.com/rooms/1305876403852901802,20260125052844,2026-01-25,city scrape,Apart estudio en Microcentro,"Located in the heart of Buenos Aires, this stu...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,25649070,https://www.airbnb.com/users/show/25649070,1465347917068117288,https://www.airbnb.com/users/profile/146534791...,Federico,NaN,11,0,3,7,"Autonomous City of Buenos Aires, Argentina",NaN,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/users/25649070/prof...,NaN,1,NaN,NaN,t,t,NaN,San Nicolas,NaN,-34.600382,-58.372692,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Paid parking on premises"", ""Air conditioning...",NaN,2.0,365.0,2.0,2.0,365.0,365.0,2.0,365.0,NaN,t,7,16,32,307,2026-01-25,1,0,0,283,1,0,NaN,2025-01-18,2025-01-18,3.00,4.00,2.00,3.00,3.00,5.00,4.00,NaN,NaN,1,1,0,0,0.08
2,1542233033640525302,https://www.airbnb.com/rooms/1542233033640525302,20260125052844,2026-01-25,city scrape,"Departamento en Buenos Aires, abasto shopping",From this central accommodation your group wil...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,153014015,https://www.airbnb.com/users/show/153014015,1468500000533080859,https://www.airbnb.com/users/profile/146850000...,Marco,NaN,8,3,7,10,"Olivos, Argentina",Responsable amable atento y amigable,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/4e988...,NaN,1,NaN,NaN,t,t,NaN,Balvanera,NaN,-34.603295,-58.409527,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,2.0,"[""Smoke alarm"", ""Wifi"", ""Kitchen"", ""Fire extin...",NaN,7.0,365.0,7.0,7.0,365.0,365.0,7.0,365.0,NaN,t,0,21,51,326,2026-01-25,0,0,0,302,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,0,NaN
3,1004530078359434134,https://www.airbnb.com/rooms/1004530078359434134,20260125052844,2026-01-25,city scrape,Departamento en Recoleta,Relax with the whole family at this peaceful p...,NaN,https://a0.muscache.com/pictures/0beb83d5-381d...,1409800,https://www.airbnb.com/users/show/1409800,1462517876404348407,https://www.airbnb.com/users/profile/146251787...,Marian,NaN,14,2,14,1,"Buenos Aires, Argentina",I'm a young entrepreneur who enjoys the pleasu...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/User-...,NaN,48,NaN,NaN,t,t,NaN,Balvanera,NaN,-34.599230,-58.407060,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Bathtub"", ""Hair dryer"", ""Exterior security c...",NaN,1.0,365.0,1.0,1.0,365.0,365.0,1.0,365.0,NaN,t,30,60,90,365,2026-01-25,22,3,0,341,3,18,NaN,2023-10-29,2025-12-07,4.73,4.64,4.64,4.82,4.73,4.59,4.45,NaN,NaN,39,34,4,0,0.80
4,800145927121871422,https://www.airbnb.com/rooms/800145927121871422,20260125052844,2026-01-25,city scrape,Coqueto para 4 personas,3 rooms: master bedroom with king size bed and...,NaN,https://a0.muscache.com/pictures/d2a502bc-2ac0...,467965425,https://www.airbnb.com/users/show/467965425,1470109782901816721,https://www.airbnb.com/users/profile/147010978...,Maria Del Carmen,NaN,3,6,2,8,"Buenos Aires, Argentina","amante de la naturaleza, aire libre y aliment...",NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/dbfd3...,NaN,2,NaN,NaN,t,t,NaN,Almagro,NaN,-34.599767,-58.426499,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,3.0,"[""Outdoor shower"", ""Dedicated workspace"", ""BBQ...",NaN,1.0,365.0,1.0,1.0,365.0,365.0,1.0,365.0,NaN,NaN,30,60,90,365,2026-01-25,0,0,0,341,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,0,0,NaN

## Nulls

In [ ]:

# 1. Preparar los datos
null_data = data.isnull().mean().reset_index()
null_data.columns = ['column', 'ratio']
null_data = null_data[null_data['ratio'] > 0].sort_values('ratio', ascending=False)

# 2. Plotear
plt.figure(figsize=(10, 6))
sns.barplot(data=null_data, x='ratio', y='column', palette='Reds_r')

# Añadimos una línea guía para el 50% o 70% (umbral común para borrar columnas)
plt.axvline(0.5, color='black', linestyle='--')
plt.title('Ratio de valores nulos por columna (Solo columnas con nulos)')
plt.xlabel('Proporción de Nulos (0.0 a 1.0)')
plt.show()

In [ ]:
# Solo columnas con al menos un nulo
cols_con_nulos = data.columns[data.isnull().any()]

# Configuramos el tamaño de la figura antes de llamar a msno
plt.figure(figsize=(12, 7))

# Personalizamos la matriz
# El color (0.2, 0.4, 0.6) es un azul acero elegante
msno.matrix(data[cols_con_nulos],
            figsize=(12, 7),
            color=(0.2, 0.4, 0.6),
            fontsize=12,
            sparkline=True,
            labels=True)

# Agregamos un título profesional con Matplotlib
plt.title('Mapa de Calor de Datos Faltantes', fontsize=20, pad=20)

plt.show()

In [ ]:
m

## Barrios

In [5]:
data.neighbourhood_cleansed.value_counts(normalize=True).round(2)

neighbourhood_cleansed
Palermo              0.33
Recoleta             0.14
San Nicolas          0.08
Belgrano             0.05
Retiro               0.05
Monserrat            0.05
Balvanera            0.04
Almagro              0.04
Villa Crespo         0.03
San Telmo            0.03
Colegiales           0.02
Chacarita            0.02
Nuñez                0.02
Caballito            0.02
Constitucion         0.01
Puerto Madero        0.01
Villa Urquiza        0.01
Barracas             0.01
Saavedra             0.01
San Cristobal        0.01
Flores               0.00
Villa Del Parque     0.00
Boca                 0.00
Coghlan              0.00
Villa Ortuzar        0.00
Boedo                0.00
Villa Devoto         0.00
Parque Patricios     0.00
Parque Chacabuco     0.00
Parque Chas          0.00
Paternal             0.00
Villa Pueyrredon     0.00
Floresta             0.00
Villa Luro           0.00
Villa Gral. Mitre    0.00
Agronomia            0.00
Liniers              0.00
Parque Avellaneda    0.00
Villa Santa Rita     0.00
Velez Sarsfield      0.00
Mataderos            0.00
Monte Castro         0.00
Nueva Pompeya        0.00
Villa Lugano         0.00
Versalles            0.00
Villa Real           0.00
Villa Soldati        0.00
Villa Riachuelo      0.00
Name: proportion, dtype: float64

## Fechas

In [6]:
data.calendar_last_scraped.value_counts()

calendar_last_scraped
2026-01-25    14113
2026-01-26    13235
Name: count, dtype: int64